
services:
  postgres:
    image: postgres:14
    container_name: postgres-db
    env_file: ./.env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d ${DB_NAME} -U ${DB_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

  kotlin-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kotlin-backend
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    env_file: ./.env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWD}
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:${DB_PORT}/${DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWD}
#    restart: on-failure
    networks:
      - backend-network
    restart: always

networks:
  backend-network:
    driver: bridge

volumes:
  postgres_data:
