
spring:
  main:
    web-application-type: servlet
  datasource:
    url: jdbc:postgresql://localhost:5432/spring-test
    username: ${DB_USER}
    password: ${DB_PASSWD}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate.ddl-auto: create-drop # update #create-drop
#    hibernate.jakarta.persistence.jdbc.url: jdbc:postgresql://localhost:5432/spring-test
    properties:
      hibernate: format_sql=true
      dialect: org.hibernate.dialect.PostgreSQLDialect # Adjust for your database

  servlet:
    multipart:
      max-file-size: 45MB
      max-request-size: 45MB
  profiles:
    active: dev

#jakarta:
#  persistence:
#    jdbc:
#      url: jdbc:postgresql://localhost:5432/spring-test

# Set logging level to DEBUG
logging:
  level:
    root: INFO
    org.springframework: DEBUG
