
spring:
  main:
    web-application-type: servlet
  datasource:
    url: jdbc:postgresql://localhost:5432/spring-test
    username: xx
    password: xx
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate: format_sql=true
      ddl-auto: update # Options: validate, create, create-drop, none
  servlet:
    multipart:
      max-file-size: 35MB
      max-request-size: 40MB
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect # Adjust for your database
  profiles:
    active: dev

# Set logging level to DEBUG
logging:
  level:
    root: DEBUG
#    affenbande: DEBUG

