spring:
  main:
    web-application-type: servlet
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWD}
  jpa:
    show-sql: true
    hibernate.ddl-auto: 'update' # update #create-drop
    properties:
      hibernate: format_sql=true
      dialect: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      max-file-size: 45MB
      max-request-size: 45MB
  profiles:
    active: dev
  mvc:
    favicon:
      enabled=false
    # TODO: Create Favicon
server:
  address: 0.0.0.0 # Listens on all network interfaces
  port: 8080       # Optional: Define the port explicitly

jakarta:
  persistence:
    jdbc:
      url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
logging:
  level:
    root: INFO
    org.springframework: DEBUG
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql: TRACE
    org.springframework.boot.SpringApplication: DEBUG

