spring:
  main:
    web-application-type: servlet
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWD}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate.ddl-auto: create-drop # update #create-drop
    properties:
      hibernate: format_sql=true
      dialect: org.hibernate.dialect.PostgreSQLDialect # Adjust for your database

  servlet:
    multipart:
      max-file-size: 45MB
      max-request-size: 45MB
  profiles:
    active: dev

# Enable JPA
jakarta:
  persistence:
    jdbc:
      url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
# Set logging level to DEBUG
logging:
  level:
    root: INFO
    org.springframework: DEBUG
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql: TRACE
    # This will print out environment variables
    org.springframework.boot.SpringApplication: DEBUG

